# Generated by Django 2.1.4 on 2018-12-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181219_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo_new',
            field=models.ImageField(default='default.jpg', upload_to='xyz'),
        ),
    ]
